# file contains code_to_course dictionary, which maps 4-letter code to its corresponding department
code_to_course = {'AAAS': 'African & African Amer Studies', 'AFSC': 'Air Force Science', 'ANTH': 'Anthropology',
                  'APPL': 'Applied Physics', 'ARAB': 'Arabic', 'ARCH': 'Architecture', 'HART': 'Art History',
                  'ASIA': 'Asian Studies', 'ASTR': 'Astronomy', 'BIOE': 'Bioengineering', 'BIOS': 'Biosciences',
                  'BUSI': 'Business', 'RCEL': 'Center Engineering Leadership', 'LEAD': 'Center for Civic Leadership',
                  'CHBE': 'Chemical & Biomolecular Eng', 'CHEM': 'Chemistry', 'CHIN': 'Chinese',
                  'CMST': 'Cinema and Media Studies', 'CEVE': 'Civil and Environmental Eng',
                  'CLAS': 'Classical Studies', 'CSCI': 'Cognitive Sciences', 'COLL': 'College Course',
                  'COMM': 'Communication', 'CAAM': 'Comp. & Applied Mathematics', 'COMP': 'Computer Science',
                  'DSCI': 'Data Science', 'DSRT': 'Dissertation/Thesis Submission',
                  'EEPS': 'Earth/Environmnt/Planetary Sci', 'ECON': 'Economics', 'EDUC': 'Education',
                  'ELEC': 'Electrical & Comp. Engineering', 'EMSP': 'Emergency Med Studies/Practice',
                  'ENGI': 'Engineering', 'ENGL': 'English', 'ENST': 'Environmental Studies', 'EURO': 'European Studies',
                  'EMBA': 'Executive Management', 'FILM': 'Film', 'FWIS': 'First-Yr Writing Intensive Sem',
                  'FREN': 'French Studies', 'GERM': 'German', 'GLBL': 'Global Affairs',
                  'GLHT': 'Global Health Technologies', 'GREE': 'Greek', 'HEAL': 'Health Sciences',
                  'HIST': 'History', 'HONS': 'Honors Program', 'HUMA': 'Humanities', 'INDE': 'Industrial Engineering',
                  'ITAL': 'Italian Language and Culture', 'JAPA': 'Japanese', 'JWST': 'Jewish Studies',
                  'KINE': 'Kinesiology', 'KORE': 'Korean', 'LATI': 'Latin', 'LALX': 'Latin American/Latinx Studies',
                  'MLSC': 'Liberal Studies Core/Capstone', 'LPAP': 'Lifetime Phys Activity Program',
                  'LING': 'Linguistics', 'MGMP': 'MBA for Professionals-Evening',
                  'MGMW': 'MBA for Professionals-Weekend', 'MGMT': 'Management', 'MACC': 'Master Accounting',
                  'MSNE': 'Materials Science & NanoEng', 'MATH': 'Mathematics', 'MECH': 'Mechanical Engineering',
                  'MDHM': 'Medical Humanities', 'MDEM': 'Medieval/Early Modern Studies', 'MILI': 'Military Science',
                  'MUCH': 'Museums and Cultural Heritage', 'MUSI': 'Music', 'NSCI': 'Natural Sciences',
                  'NAVA': 'Naval Science', 'NEUR': 'Neuroscience', 'PHIL': 'Philosophy', 'FOTO': 'Photography',
                  'PHYS': 'Physics', 'POLI': 'Political Science', 'PLST': 'Politics, Law, Social Thought',
                  'PORT': 'Portuguese', 'PJHC': 'Poverty/Justice/Hum Capability', 'PSYC': 'Psychology',
                  'RELI': 'Religion', 'RUSS': 'Russian', 'SOPA': 'Social Policy Analysis',
                  'SOPE': 'Social Policy Evaluation', 'SOSC': 'Social Sciences', 'SOCI': 'Sociology', 'SPAN': 'Spanish',
                  'SPPO': 'Spanish and Portuguese', 'SMGT': 'Sport Management', 'STAT': 'Statistics',
                  'SSPB': 'Systems/Synthetic/Phys Biology', 'THEA': 'Theatre', 'UNIV': 'University Courses',
                  'ARTS': 'Visual Arts', 'SWGS': 'Women, Gender, & Sexuality'}
